import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Plus, Search } from "lucide-react";
import { useLiveAlerts } from "../hooks/useLiveAlerts";
import { routePatientId } from "../services/api";

export default function Patients() {
  const [search, setSearch] = useState("");
  const [severityFilter, setSeverityFilter] = useState("all");
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [currentPage, setCurrentPage] = useState(1);
  const [showAddPatientForm, setShowAddPatientForm] = useState(false);
  const [draftPatients, setDraftPatients] = useState([]);
  const [draftForm, setDraftForm] = useState({
    id: "P9001",
    name: "New Patient",
    disease: "General Review",
    severity: "Moderate",
    organ: "General",
  });
  const navigate = useNavigate();
  const { patients, isLoading, error, lastUpdated } = useLiveAlerts();

  const filteredPatients = patients.filter((patient) => {
    const matchesSearch =
      patient.id.toLowerCase().includes(search.toLowerCase()) ||
      patient.name.toLowerCase().includes(search.toLowerCase()) ||
      patient.disease.toLowerCase().includes(search.toLowerCase()) ||
      patient.organ.toLowerCase().includes(search.toLowerCase());

    const matchesSeverity =
      severityFilter === "all" || patient.severity === severityFilter;

    return matchesSearch && matchesSeverity;
  });

  const totalPages = Math.ceil(filteredPatients.length / rowsPerPage);
  const startIdx = (currentPage - 1) * rowsPerPage;
  const paginatedPatients = filteredPatients.slice(startIdx, startIdx + rowsPerPage);

  return (
    <div className="space-y-8">
      <div className="rounded-[32px] bg-white p-8 shadow-sm ring-1 ring-slate-200">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <p className="text-sm uppercase tracking-[0.3em] text-slate-500">Patient management</p>
            <h1 className="mt-2 text-4xl font-semibold text-slate-900">Patient Details</h1>
            <p className="mt-3 max-w-2xl text-sm text-slate-500">
              Search and review live patient records generated by WhatsApp triage alerts.
            </p>
            <p className="mt-2 text-xs font-semibold text-slate-400">
              {lastUpdated ? `Last synced ${lastUpdated.toLocaleTimeString()}` : "Connecting to backend alerts..."}
            </p>
          </div>
          <button
            onClick={() => setShowAddPatientForm((current) => !current)}
            className="inline-flex items-center gap-2 rounded-3xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-emerald-500"
          >
            <Plus size={20} />
            {showAddPatientForm ? "Hide draft form" : "Add Patient"}
          </button>
        </div>
      </div>

      {showAddPatientForm && (
        <div className="rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
          <div className="mb-4 flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-slate-900">Patient draft workspace</p>
              <p className="mt-1 text-sm text-slate-500">Create a draft entry for review before adding it to the local queue.</p>
            </div>
            <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">
              {draftPatients.length} draft{draftPatients.length === 1 ? "" : "s"}
            </span>
          </div>

          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
            <label className="text-sm font-semibold text-slate-700">
              Patient ID
              <input
                value={draftForm.id}
                onChange={(event) => setDraftForm((current) => ({ ...current, id: event.target.value }))}
                className="mt-2 w-full rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700 outline-none"
              />
            </label>
            <label className="text-sm font-semibold text-slate-700">
              Name
              <input
                value={draftForm.name}
                onChange={(event) => setDraftForm((current) => ({ ...current, name: event.target.value }))}
                className="mt-2 w-full rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700 outline-none"
              />
            </label>
            <label className="text-sm font-semibold text-slate-700">
              Disease
              <input
                value={draftForm.disease}
                onChange={(event) => setDraftForm((current) => ({ ...current, disease: event.target.value }))}
                className="mt-2 w-full rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700 outline-none"
              />
            </label>
            <label className="text-sm font-semibold text-slate-700">
              Organ
              <input
                value={draftForm.organ}
                onChange={(event) => setDraftForm((current) => ({ ...current, organ: event.target.value }))}
                className="mt-2 w-full rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700 outline-none"
              />
            </label>
            <label className="text-sm font-semibold text-slate-700">
              Severity
              <select
                value={draftForm.severity}
                onChange={(event) => setDraftForm((current) => ({ ...current, severity: event.target.value }))}
                className="mt-2 w-full rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700 outline-none"
              >
                <option value="Critical">Critical</option>
                <option value="Moderate">Moderate</option>
                <option value="Low">Low</option>
              </select>
            </label>
          </div>

          <div className="mt-4 flex flex-wrap gap-3">
            <button
              onClick={() => {
                setDraftPatients((current) => [
                  {
                    ...draftForm,
                    addedAt: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
                  },
                  ...current,
                ]);
                setDraftForm({
                  id: `P${Math.floor(9000 + Math.random() * 1000)}`,
                  name: "New Patient",
                  disease: "General Review",
                  severity: "Moderate",
                  organ: "General",
                });
              }}
              className="rounded-3xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800"
            >
              Save draft
            </button>
            <button
              onClick={() => setShowAddPatientForm(false)}
              className="rounded-3xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-900 transition hover:bg-slate-50"
            >
              Close
            </button>
          </div>
        </div>
      )}

      {error && (
        <div className="rounded-[28px] bg-red-50 px-5 py-4 text-sm font-semibold text-red-700 ring-1 ring-red-200">
          Backend connection issue: {error}
        </div>
      )}

      {draftPatients.length > 0 && (
        <div className="rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
          <div className="mb-4 flex items-center justify-between gap-4">
            <div>
              <p className="text-sm font-semibold text-slate-900">Local draft queue</p>
              <p className="mt-1 text-sm text-slate-500">Drafts created locally for review and onboarding.</p>
            </div>
          </div>

          <div className="grid gap-3 md:grid-cols-2">
            {draftPatients.map((draft, index) => (
              <div key={`${draft.id}-${index}`} className="rounded-[28px] bg-slate-50 p-4 ring-1 ring-slate-200">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-900">{draft.name}</p>
                    <p className="mt-1 text-xs text-slate-500">{draft.id} • {draft.organ}</p>
                  </div>
                  <span className={`rounded-full px-3 py-1 text-xs font-semibold ${
                    draft.severity === "Critical"
                      ? "bg-red-100 text-red-700"
                      : draft.severity === "Moderate"
                      ? "bg-amber-100 text-amber-700"
                      : "bg-emerald-100 text-emerald-700"
                  }`}>
                    {draft.severity}
                  </span>
                </div>
                <p className="mt-3 text-sm text-slate-600">{draft.disease}</p>
                <p className="mt-2 text-xs text-slate-500">Draft saved at {draft.addedAt}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SEVERITY FILTER CHIPS */}
      <div className="rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
        <p className="text-sm font-semibold text-slate-900 mb-4">Filter by severity</p>
        <div className="flex flex-wrap gap-2">
          {["all", "Critical", "Moderate", "Low"].map((severity) => (
            <button
              key={severity}
              onClick={() => {
                setSeverityFilter(severity);
                setCurrentPage(1);
              }}
              className={`rounded-3xl px-4 py-2 text-sm font-semibold transition ${
                severityFilter === severity
                  ? severity === "all"
                    ? "bg-slate-900 text-white"
                    : severity === "Critical"
                    ? "bg-red-600 text-white"
                    : severity === "Moderate"
                    ? "bg-amber-600 text-white"
                    : "bg-emerald-600 text-white"
                  : "bg-slate-100 text-slate-700 hover:bg-slate-200"
              }`}
            >
              {severity === "all" ? "All Patients" : severity}
            </button>
          ))}
        </div>
      </div>

      {/* SEARCH & INFO */}
      <div className="rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex-1 max-w-[420px]">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400" />
              <input
                type="text"
                placeholder="Search by ID, Name, Disease, Organ..."
                className="w-full rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 pl-12 text-sm outline-none transition focus:border-slate-400 focus:bg-white"
                value={search}
                onChange={(e) => {
                  setSearch(e.target.value);
                  setCurrentPage(1);
                }}
              />
            </div>
          </div>
          <div className="flex items-center gap-3 text-sm">
            <span className="font-semibold text-slate-900">Rows per page:</span>
            <select
              value={rowsPerPage}
              onChange={(e) => {
                setRowsPerPage(Number(e.target.value));
                setCurrentPage(1);
              }}
              className="rounded-3xl bg-slate-100 px-4 py-2 font-semibold text-slate-700 outline-none hover:bg-slate-200 transition"
            >
              <option value={10}>10</option>
              <option value={25}>25</option>
              <option value={50}>50</option>
            </select>
          </div>
        </div>
        <div className="mt-4 text-sm text-slate-600">
          Showing <span className="font-semibold text-slate-900">{paginatedPatients.length}</span> of{" "}
          <span className="font-semibold text-slate-900">{filteredPatients.length}</span> patients
        </div>
      </div>

      {/* TABLE */}
      <div className="overflow-x-auto rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
        <table className="w-full min-w-[900px] border-separate border-spacing-y-3">
          <thead>
            <tr className="text-left text-sm uppercase tracking-[0.24em] text-slate-500">
              <th className="pb-4 font-semibold">ID</th>
              <th className="pb-4 font-semibold">Name</th>
              <th className="pb-4 font-semibold">Severity</th>
              <th className="pb-4 font-semibold">Disease</th>
              <th className="pb-4 font-semibold">Admitted</th>
              <th className="pb-4 font-semibold">Organ</th>
              <th className="pb-4 font-semibold">Age</th>
              <th className="pb-4 text-center font-semibold">Action</th>
            </tr>
          </thead>
          <tbody>
            {paginatedPatients.map((patient) => (
              <tr
                key={patient.id}
                className="rounded-[28px] bg-slate-50 text-sm text-slate-700 transition hover:bg-slate-100 hover:shadow-md"
              >
                <td className="py-4 font-mono font-semibold text-slate-900">{patient.id}</td>
                <td className="py-4 font-semibold text-slate-900">{patient.name}</td>
                <td className="py-4">
                  <span
                    className={`inline-flex rounded-full px-4 py-2 text-xs font-semibold ${
                      patient.severity === "Critical"
                        ? "bg-red-100 text-red-700"
                        : patient.severity === "Moderate"
                        ? "bg-amber-100 text-amber-700"
                        : "bg-emerald-100 text-emerald-700"
                    }`}
                  >
                    {patient.severity}
                  </span>
                </td>
                <td className="py-4">{patient.disease}</td>
                <td className="py-4">
                  <span className={`font-semibold ${patient.admitted === "Yes" ? "text-red-600" : "text-emerald-600"}`}>
                    {patient.admitted}
                  </span>
                </td>
                <td className="py-4">{patient.organ}</td>
                <td className="py-4">{patient.age}</td>
                <td className="py-4 text-center">
                  <button
                    onClick={() => navigate(`/patients/${routePatientId(patient.id)}`)}
                    className="rounded-3xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-slate-50 hover:border-slate-300"
                  >
                    View profile
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {paginatedPatients.length === 0 && (
          <div className="text-center py-12">
            <p className="text-slate-600">
              {isLoading ? "Loading live patients..." : "No live patients found matching your criteria"}
            </p>
          </div>
        )}
      </div>

      {/* PAGINATION */}
      {totalPages > 1 && (
        <div className="rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200 flex items-center justify-between">
          <div className="text-sm text-slate-600">
            Page <span className="font-semibold text-slate-900">{currentPage}</span> of{" "}
            <span className="font-semibold text-slate-900">{totalPages}</span>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => setCurrentPage(Math.max(1, currentPage - 1))}
              disabled={currentPage === 1}
              className="rounded-3xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              ← Previous
            </button>
            <button
              onClick={() => setCurrentPage(Math.min(totalPages, currentPage + 1))}
              disabled={currentPage === totalPages}
              className="rounded-3xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-slate-50 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              Next →
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
