import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Search } from "lucide-react";
import { useLiveAlerts } from "../hooks/useLiveAlerts";
import { routePatientId } from "../services/api";

export default function Patients() {
  const [search, setSearch] = useState("");
  const [severityFilter, setSeverityFilter] = useState("all");
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [currentPage, setCurrentPage] = useState(1);
  const navigate = useNavigate();
  const { patients, isLoading, error, lastUpdated } = useLiveAlerts();

  const filteredPatients = patients.filter((patient) => {
    const normalizedSearch = search.toLowerCase();
    const matchesSearch =
      patient.id.toLowerCase().includes(normalizedSearch) ||
      patient.name.toLowerCase().includes(normalizedSearch) ||
      patient.disease.toLowerCase().includes(normalizedSearch) ||
      patient.organ.toLowerCase().includes(normalizedSearch);

    const matchesSeverity =
      severityFilter === "all" || patient.severity === severityFilter;

    return matchesSearch && matchesSeverity;
  });

  const totalPages = Math.ceil(filteredPatients.length / rowsPerPage);
  const startIdx = (currentPage - 1) * rowsPerPage;
  const paginatedPatients = filteredPatients.slice(startIdx, startIdx + rowsPerPage);

  return (
    <div className="space-y-8">
      <div className="rounded-[32px] bg-white p-8 shadow-sm ring-1 ring-slate-200">
        <div>
          <p className="text-sm uppercase tracking-[0.3em] text-slate-500">Patient management</p>
          <h1 className="mt-2 text-4xl font-semibold text-slate-900">Patient Details</h1>
          <p className="mt-3 max-w-2xl text-sm text-slate-500">
            Search and review live patient records generated by backend triage alerts.
          </p>
          <p className="mt-2 text-xs font-semibold text-slate-400">
            {lastUpdated ? `Last synced ${lastUpdated.toLocaleTimeString()}` : "Connecting to backend alerts..."}
          </p>
        </div>
      </div>

      {error && (
        <div className="rounded-[28px] bg-red-50 px-5 py-4 text-sm font-semibold text-red-700 ring-1 ring-red-200">
          Backend connection issue: {error}
        </div>
      )}

      <div className="rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
        <p className="mb-4 text-sm font-semibold text-slate-900">Filter by severity</p>
        <div className="flex flex-wrap gap-2">
          {["all", "Critical", "Moderate", "Low"].map((severity) => (
            <button
              key={severity}
              onClick={() => {
                setSeverityFilter(severity);
                setCurrentPage(1);
              }}
              className={`rounded-3xl px-4 py-2 text-sm font-semibold transition ${
                severityFilter === severity
                  ? severity === "all"
                    ? "bg-slate-900 text-white"
                    : severity === "Critical"
                      ? "bg-red-600 text-white"
                      : severity === "Moderate"
                        ? "bg-amber-600 text-white"
                        : "bg-emerald-600 text-white"
                  : "bg-slate-100 text-slate-700 hover:bg-slate-200"
              }`}
            >
              {severity === "all" ? "All Patients" : severity}
            </button>
          ))}
        </div>
      </div>

      <div className="rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="max-w-[420px] flex-1">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                placeholder="Search live patients"
                className="w-full rounded-3xl border border-slate-200 bg-slate-50 px-4 py-3 pl-12 text-sm outline-none transition focus:border-slate-400 focus:bg-white"
                value={search}
                onChange={(event) => {
                  setSearch(event.target.value);
                  setCurrentPage(1);
                }}
              />
            </div>
          </div>
          <div className="flex items-center gap-3 text-sm">
            <span className="font-semibold text-slate-900">Rows per page:</span>
            <select
              value={rowsPerPage}
              onChange={(event) => {
                setRowsPerPage(Number(event.target.value));
                setCurrentPage(1);
              }}
              className="rounded-3xl bg-slate-100 px-4 py-2 font-semibold text-slate-700 outline-none transition hover:bg-slate-200"
            >
              <option value={10}>10</option>
              <option value={25}>25</option>
              <option value={50}>50</option>
            </select>
          </div>
        </div>
        <div className="mt-4 text-sm text-slate-600">
          Showing <span className="font-semibold text-slate-900">{paginatedPatients.length}</span> of{" "}
          <span className="font-semibold text-slate-900">{filteredPatients.length}</span> live patients
        </div>
      </div>

      <div className="overflow-x-auto rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
        <table className="w-full min-w-[900px] border-separate border-spacing-y-3">
          <thead>
            <tr className="text-left text-sm uppercase tracking-[0.24em] text-slate-500">
              <th className="pb-4 font-semibold">ID</th>
              <th className="pb-4 font-semibold">Name</th>
              <th className="pb-4 font-semibold">Severity</th>
              <th className="pb-4 font-semibold">Issue</th>
              <th className="pb-4 font-semibold">Admitted</th>
              <th className="pb-4 font-semibold">Organ</th>
              <th className="pb-4 font-semibold">Age</th>
              <th className="pb-4 text-center font-semibold">Action</th>
            </tr>
          </thead>
          <tbody>
            {paginatedPatients.map((patient) => (
              <tr
                key={patient.id}
                className="rounded-[28px] bg-slate-50 text-sm text-slate-700 transition hover:bg-slate-100 hover:shadow-md"
              >
                <td className="py-4 font-mono font-semibold text-slate-900">{patient.id}</td>
                <td className="py-4 font-semibold text-slate-900">{patient.name}</td>
                <td className="py-4">
                  <span
                    className={`inline-flex rounded-full px-4 py-2 text-xs font-semibold ${
                      patient.severity === "Critical"
                        ? "bg-red-100 text-red-700"
                        : patient.severity === "Moderate"
                          ? "bg-amber-100 text-amber-700"
                          : "bg-emerald-100 text-emerald-700"
                    }`}
                  >
                    {patient.severity}
                  </span>
                </td>
                <td className="py-4">{patient.disease}</td>
                <td className="py-4">
                  <span className={`font-semibold ${patient.admitted === "Yes" ? "text-red-600" : "text-emerald-600"}`}>
                    {patient.admitted}
                  </span>
                </td>
                <td className="py-4">{patient.organ}</td>
                <td className="py-4">{patient.age}</td>
                <td className="py-4 text-center">
                  <button
                    onClick={() => navigate(`/patients/${routePatientId(patient.id)}`)}
                    className="rounded-3xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-900 transition hover:border-slate-300 hover:bg-slate-50"
                  >
                    View profile
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {paginatedPatients.length === 0 && (
          <div className="py-12 text-center">
            <p className="text-slate-600">
              {isLoading ? "Loading live patients..." : "No live patients found."}
            </p>
          </div>
        )}
      </div>

      {totalPages > 1 && (
        <div className="flex items-center justify-between rounded-[32px] bg-white p-6 shadow-sm ring-1 ring-slate-200">
          <div className="text-sm text-slate-600">
            Page <span className="font-semibold text-slate-900">{currentPage}</span> of{" "}
            <span className="font-semibold text-slate-900">{totalPages}</span>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => setCurrentPage(Math.max(1, currentPage - 1))}
              disabled={currentPage === 1}
              className="rounded-3xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Previous
            </button>
            <button
              onClick={() => setCurrentPage(Math.min(totalPages, currentPage + 1))}
              disabled={currentPage === totalPages}
              className="rounded-3xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Next
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
